AWSTemplateFormatVersion: 2010-09-09
Description: jat-app

Transform:
  - AWS::Serverless-2016-10-31

Resources:

  JobApplicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JobApplications
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/createApplication.createApplicationHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          TABLE_NAME: JobApplications
      Events:
        CreateApplicationApi:
          Type: Api
          Properties:
            Path: /applications
            Method: POST
            RestApiId: !Ref MyApi
            
      Policies:
        - DynamoDBCrudPolicy:
            TableName: JobApplications

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: 
      Fn::Sub: "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications"
